In [10]:
import pandas as pd
from utils import check_nas, unique_values, values_only_in_set

### 1. Load dataset

In [11]:
train = pd.read_csv('data/train.csv', index_col=0, low_memory=False)
test = pd.read_csv('data/test.csv', index_col=0, low_memory=False)

### 2. Check for NAs

Check no. missing values for Train

In [12]:
check_nas(train,'FIELD_3')

(463, 0.015433333333333334)

Check no. missing value for Test

In [13]:
check_nas(test,'FIELD_3')

(325, 0.010833333333333334)

### 3. Check for Unique Values

#### Similar Unique values in Train & Test

In [20]:
set(train.FIELD_3.unique()).intersection(set(test.FIELD_3.unique()))

{-1.0,
 337.0,
 338.0,
 339.0,
 340.0,
 341.0,
 342.0,
 343.0,
 344.0,
 345.0,
 346.0,
 347.0,
 348.0,
 349.0,
 350.0,
 351.0,
 352.0,
 353.0,
 354.0,
 355.0,
 356.0,
 357.0,
 358.0,
 359.0,
 360.0,
 361.0,
 362.0,
 363.0,
 364.0,
 365.0,
 366.0,
 367.0,
 702.0,
 703.0,
 704.0,
 705.0,
 706.0,
 707.0,
 708.0,
 709.0,
 710.0,
 711.0,
 712.0,
 713.0,
 714.0,
 715.0,
 716.0,
 717.0,
 718.0,
 719.0,
 720.0,
 721.0,
 722.0,
 723.0,
 724.0,
 725.0,
 726.0,
 727.0,
 728.0,
 729.0,
 730.0,
 731.0,
 732.0,
 1067.0,
 1068.0,
 1069.0,
 1070.0,
 1071.0,
 1072.0,
 1073.0,
 1074.0,
 1075.0,
 1076.0,
 1077.0,
 1078.0,
 1079.0,
 1080.0,
 1081.0,
 1082.0,
 1083.0,
 1084.0,
 1085.0,
 1086.0,
 1087.0,
 1088.0,
 1089.0,
 1090.0,
 1091.0,
 1092.0,
 1093.0,
 1094.0,
 1095.0,
 1096.0,
 1097.0,
 1433.0,
 1434.0,
 1435.0,
 1436.0,
 1437.0,
 1438.0,
 1439.0,
 1440.0,
 1441.0,
 1442.0,
 1443.0,
 1444.0,
 1445.0,
 1446.0,
 1447.0,
 1448.0,
 1449.0,
 1450.0,
 1451.0,
 1452.0,
 1453.0,
 1454.0,
 1455.0,
 1456.0,
 1457.0,
 1458.0,
 1459.0,
 1460.0,
 1461.0,
 1462.0,
 1463.0,
 1798.0,
 1799.0,
 1800.0,
 1801.0,
 1802.0,
 1803.0,
 1804.0,
 1805.0,
 1806.0,
 1807.0,
 1808.0,
 1809.0,
 1810.0,
 1811.0,
 1812.0,
 1813.0,
 1814.0,
 1815.0,
 1816.0,
 1817.0,
 1818.0,
 1819.0,
 1820.0,
 1821.0,
 1822.0,
 1823.0,
 1824.0,
 1825.0,
 1826.0,
 1827.0,
 1828.0,
 2163.0,
 2164.0,
 2165.0,
 2166.0,
 2167.0,
 2168.0,
 2169.0,
 2170.0,
 2171.0,
 2172.0,
 2173.0,
 2174.0,
 2175.0,
 2176.0,
 2177.0,
 2178.0,
 2179.0,
 2180.0,
 2181.0,
 2182.0,
 2183.0,
 2184.0,
 2185.0,
 2186.0,
 2187.0,
 2188.0,
 2189.0,
 2190.0,
 2191.0,
 2192.0,
 2193.0,
 2528.0,
 2529.0,
 2530.0,
 2531.0,
 2532.0,
 2533.0,
 2534.0,
 2535.0,
 2536.0,
 2537.0,
 2538.0,
 2539.0,
 2540.0,
 2541.0,
 2542.0,
 2543.0,
 2544.0,
 2545.0,
 2546.0,
 2547.0,
 2548.0,
 2549.0,
 2550.0,
 2551.0,
 2552.0,
 2553.0,
 2554.0,
 2555.0,
 2556.0,
 2557.0,
 2558.0,
 2894.0,
 2895.0,
 2896.0,
 2897.0,
 2898.0,
 2899.0,
 2900.0,
 2901.0,
 2902.0,
 2903.0,
 2904.0,
 2905.0,
 2906.0,
 2907.0,
 2908.0,
 2909.0,
 2910.0,
 2911.0,
 2912.0,
 2913.0,
 2914.0,
 2915.0,
 2916.0,
 2917.0,
 2918.0,
 2919.0,
 2920.0,
 2921.0,
 2922.0,
 2923.0,
 2924.0,
 3259.0,
 3260.0,
 3261.0,
 3262.0,
 3263.0,
 3264.0,
 3265.0,
 3266.0,
 3267.0,
 3268.0,
 3269.0,
 3270.0,
 3271.0,
 3272.0,
 3273.0,
 3274.0,
 3275.0,
 3276.0,
 3277.0,
 3278.0,
 3279.0,
 3280.0,
 3281.0,
 3282.0,
 3283.0,
 3284.0,
 3285.0,
 3286.0,
 3287.0,
 3288.0,
 3289.0,
 3624.0,
 3625.0,
 3626.0,
 3627.0,
 3628.0,
 3629.0,
 3630.0,
 3631.0,
 3632.0,
 3633.0,
 3634.0,
 3635.0,
 3636.0,
 3637.0,
 3638.0,
 3639.0,
 3640.0,
 3641.0,
 3642.0,
 3643.0,
 3644.0,
 3645.0,
 3646.0,
 3647.0,
 3648.0,
 3649.0,
 3650.0,
 3651.0,
 3652.0,
 3653.0,
 3654.0,
 3989.0,
 3990.0,
 3991.0,
 3992.0,
 3993.0,
 3994.0,
 3995.0,
 3996.0,
 3997.0,
 3998.0,
 3999.0,
 4000.0,
 4001.0,
 4002.0,
 4003.0,
 4004.0,
 4005.0,
 4006.0,
 4007.0,
 4008.0,
 4009.0,
 4010.0,
 4011.0,
 4012.0,
 4013.0,
 4014.0,
 4015.0,
 4016.0,
 4017.0,
 4018.0,
 4019.0,
 4355.0,
 4356.0,
 4357.0,
 4358.0,
 4359.0,
 4360.0,
 4361.0,
 4362.0,
 4363.0,
 4364.0,
 4365.0,
 4366.0,
 4367.0,
 4368.0,
 4370.0,
 4371.0,
 4372.0,
 4373.0,
 4374.0,
 4375.0,
 4376.0,
 4377.0,
 4378.0,
 4379.0,
 4380.0,
 4381.0,
 4382.0,
 4383.0,
 4384.0,
 4385.0,
 4722.0,
 4723.0,
 4725.0,
 4726.0,
 4728.0,
 4729.0,
 4733.0,
 4735.0,
 4739.0,
 4740.0,
 4742.0,
 4745.0,
 4746.0,
 5085.0,
 5089.0,
 5096.0,
 5102.0,
 5103.0,
 5104.0,
 5105.0,
 5452.0,
 5457.0,
 5460.0,
 5462.0,
 5463.0,
 5467.0,
 5471.0,
 5479.0,
 5480.0,
 5818.0,
 5834.0,
 6181.0,
 6188.0,
 6204.0,
 6209.0,
 6546.0,
 6551.0,
 6570.0,
 6914.0,
 7650.0,
 7651.0,
 7660.0,
 7668.0,
 7669.0,
 7671.0,
 8009.0,
 8010.0,
 8012.0,
 8013.0,
 8014.0,
 8016.0,
 8017.0,
 8021.0,
 8026.0,
 8032.0,
 8036.0,
 8037.0}

#### Unique values in Train

In [15]:
unique_values(train,'FIELD_3')

(-1.0       6996
  4019.0     199
  3993.0     180
  3997.0     153
  2901.0     148
            ...
  6932.0       1
  4743.0       1
  4750.0       1
  8019.0       1
  6553.0       1
 Name: FIELD_3, Length: 513, dtype: int64, -1.0       0.236855
  4019.0    0.006737
  3993.0    0.006094
  3997.0    0.005180
  2901.0    0.005011
              ...
  6932.0    0.000034
  4743.0    0.000034
  4750.0    0.000034
  8019.0    0.000034
  6553.0    0.000034
 Name: FIELD_3, Length: 513, dtype: float64)

#### Unique values in Test

In [16]:
unique_values(test,'FIELD_3')

(-1.0       4716
  3997.0     117
  4019.0     108
  3993.0     106
  2901.0      96
            ...
  5829.0       1
  5479.0       1
  5104.0       1
  6187.0       1
  6561.0       1
 Name: FIELD_3, Length: 472, dtype: int64, -1.0       0.239695
  3997.0    0.005947
  4019.0    0.005489
  3993.0    0.005388
  2901.0    0.004879
              ...
  5829.0    0.000051
  5479.0    0.000051
  5104.0    0.000051
  6187.0    0.000051
  6561.0    0.000051
 Name: FIELD_3, Length: 472, dtype: float64)

### 4. Compare Train and Test

Compare Unique values only in Train

In [17]:
values_only_in_set(train, test, 'FIELD_3')

({nan,
  4369.0,
  4724.0,
  4727.0,
  4731.0,
  4732.0,
  4734.0,
  4736.0,
  4737.0,
  4738.0,
  4741.0,
  4743.0,
  4747.0,
  4749.0,
  4750.0,
  5086.0,
  5087.0,
  5091.0,
  5095.0,
  5106.0,
  5107.0,
  5111.0,
  5112.0,
  5450.0,
  5451.0,
  5453.0,
  5454.0,
  5461.0,
  5465.0,
  5469.0,
  5474.0,
  5819.0,
  5823.0,
  5826.0,
  5827.0,
  5828.0,
  5832.0,
  5836.0,
  5839.0,
  5840.0,
  5846.0,
  6183.0,
  6184.0,
  6196.0,
  6197.0,
  6201.0,
  6203.0,
  6205.0,
  6206.0,
  6210.0,
  6548.0,
  6549.0,
  6553.0,
  6555.0,
  6559.0,
  6563.0,
  6916.0,
  6932.0,
  6935.0,
  6936.0,
  6937.0,
  6940.0,
  7279.0,
  7281.0,
  7284.0,
  7291.0,
  7299.0,
  7307.0,
  7643.0,
  7645.0,
  7648.0,
  7649.0,
  7652.0,
  7657.0,
  7658.0,
  7662.0,
  7665.0,
  7672.0,
  8011.0,
  8018.0,
  8019.0,
  8020.0,
  8029.0,
  8030.0,
  8035.0},
 85)

Compare Unique values only in Test

In [18]:
values_only_in_set(test, train, 'FIELD_3')

({nan,
  4744.0,
  4748.0,
  5088.0,
  5093.0,
  5097.0,
  5455.0,
  5466.0,
  5470.0,
  5472.0,
  5478.0,
  5820.0,
  5824.0,
  5829.0,
  5833.0,
  5837.0,
  5838.0,
  5845.0,
  6187.0,
  6195.0,
  6202.0,
  6552.0,
  6561.0,
  6572.0,
  6573.0,
  6575.0,
  6917.0,
  6925.0,
  6931.0,
  6933.0,
  6934.0,
  7283.0,
  7289.0,
  7298.0,
  7300.0,
  7301.0,
  7644.0,
  7663.0,
  7670.0,
  8015.0,
  8023.0,
  8024.0,
  8031.0,
  8033.0},
 44)