In [1]:
import pandas as pd
import numpy as np
from utils import replace_by_column

### Load dataset

In [2]:
data = pd.read_csv('train.csv', index_col=0)

/home/ttn/miniconda3/envs/ml/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2714: DtypeWarning: Columns (51) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data.head(3)

,label,province,district,age_source1,age_source2,maCv,FIELD_1,FIELD_2,FIELD_3,FIELD_4,...,FIELD_48,FIELD_49,FIELD_50,FIELD_51,FIELD_52,FIELD_53,FIELD_54,FIELD_55,FIELD_56,FIELD_57
id,,,,,,,,,,,,,,,,,,,,,
0,0,NaN,NaN,NaN,NaN,NaN,1,1.0,2547.0,0.0,...,True,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,Tỉnh Đồng Nai,Thành phố Biên Hòa,44.0,44.0,None,1,0.0,-1.0,1.0,...,False,True,29.77,17.561,30.955,31.171,0.0,0.04,0.0,0.0
2,0,Tỉnh Đồng Nai,Huyện Long Thành,30.0,30.0,Công nhân,0,1.0,3273.0,1.0,...,True,True,29.77,56.512,30.955,31.171,0.0,0.16,0.0,0.0

### 1. Check nan value

In [4]:
pd.isna(data.maCv).sum()

9679

### 2. Lowercase for Categorical data

In [5]:
data.maCv = data.maCv.str.lower()

### 3. Count unique values

Replace repeated values - None by Nan

In [6]:
data.maCv = data.maCv.replace('none',np.nan)

Replace 'công nhân' variations

In [7]:
replace_by_column(data, 'maCv', ['nv','n.v','nhân viên','nhân vieen', 'nhân  viên', 'sales', 'bảo trì','giao','tạp vụ', 
                              'văn thư','thư ký','thư kí','kế toán','kế tóan','trợ lí','trợ lys','trợ lý','tiếp thị','bán hàng',
                              'khách hangf','sale','bảo veej','bảo vệ','tap vu','tạp','kiểm tra','khách hàng','chuyên viên','nhâ viên',
                             'thu ngân','pha chế','hành chính','hành chánh','giỏo viờn','tiếp viên','bóc','kinh doanh','chăm sóc','b. vệ',
                              'b.ve', 'b.vệ','chuyên  viên','tổng đài','thiết kế','thao tác viên','dịch vụ','lấy dấu','lưu trữ viên',
                              'thống kê','qc','mậu dịch viên','tín dụng','kế toán','thường trực','chuyên dùng','nội dung'],'nhân viên')

In [8]:
replace_by_column(data, 'maCv', ['thợ','coõng nhaõn','cắt','phụ','may','xn','xí nghiejep','xí nghiệp','sơn','cao su','giày',
                              'thô','lao động','lđ','vh','vận hành','kiểm hóa','thành hình','lắp','bốc','xd','xây dựng',
                              'xây','chất lượng','mài', 'trải','đóng','cơ khí','nặng nhọc','khai thác','chế tác','bôi',
                              'chuyền','thêu','sấy','lò','xưởng','ép','áp suất','cạo mủ','gò hàn','mộc máy','hoàn tất',
                              'chuẩn bị','hàn điện','phân cỡ','khiêng khuôn','tỉa biên','gò dán','làm mác','phan loai',
                             'kiem tra','x9-vat tu sat','điện máy','kcs','hỗ trợ sản xuất','thắt dây','xử lý'],'công nhân')

In [9]:
replace_by_column(data, 'maCv', ['y tá','y sỹ','hộ sinh','điều dưỡng','hộ lí','hộ lý','y tế'], 'y tá')

In [10]:
replace_by_column(data, 'maCv', ['gv','g.v','giáo viên','giaó viên','gíao viên','trường th thanh hưng','trung cấp mầm non','giáo  viên','đào tạo'], 'giáo viên')

In [11]:
replace_by_column(data, 'maCv', ['bác sĩ','bs','b.s','bác sỹ','trị liệu'], 'bác sĩ')

In [12]:
replace_by_column(data, 'maCv', ['cán bộ','cb','c.b','bí thư','kiểm','cấp dưỡng','hộ tịch','khuyến nông','bí tư','thanh tra','viên chức','ủy nhiệm'], 'cán bộ')

In [13]:
replace_by_column(data, 'maCv', ['quản lý','quản lí','giám sát','gíam sát','trưởng nhóm','phongf','phòng','trưởng','phó','quản',
                              'ủy nhiệm','ban','thủ','ql','ủy','qu?n lý','senior','giám định','hàng trưởng','qu?n lý xu?ng',
                              'cửa hàng trưởng','thu? kho','đại diện','qu?n lý xu?ng'], 'quản lý cấp trung')

In [14]:
replace_by_column(data, 'maCv', ['giám đốc','gíam đốc', 'chủ tịch','gd','executive','điều hành','p.gđốc'], 'quản lý cấp cao')

In [15]:
replace_by_column(data, 'maCv', ['kĩ sư','kỹ sư','kĩ thuật viên','kỹ thuật vieen','kỹ thuật viên','ktv','kĩ thuật','kỹ thuật',
                              'lập trình','k? thu?t viờn','kỷ thuật','sửa chữa','chữa','operator', 'k? thu?t viờn','nghiên cứu viên'], 'kỹ sư')

In [16]:
replace_by_column(data, 'maCv', ['lái xe','lái máy','lái cẩu','tài xế xáng cạp','tài xế','tài xê', 'lỏi xe'], 'lái xe')

In [17]:
replace_by_column(data, 'maCv', ['bếp','nấu ăn'], 'đầu bếp')

In [18]:
replace_by_column(data, 'maCv', ['dược'], 'dược sĩ')

In [19]:
replace_by_column(data, 'maCv', ['chỉ huy','sĩ quan'], 'quân đội')

In [20]:
data.maCv = data.maCv.replace(['2983','qc point 7','thieu chuc danh tu du lieu 3s','10958', '5339',
       '1006481','147','1020096','0','2853','vn.5061','135','8059', '4999','1020883','1006694','ho chi minh'],np.nan)

In [268]:
data.maCv = data.maCv.replace('cô nuôi','bảo mẫu')

In [285]:
data.maCv = data.maCv.replace(['cod','trạm nghiền','nnđh','kt cam','chi?u x? th','hoist','btđ tncshcm','đdth'],'khác')

In [327]:
data.maCv = data.maCv.replace(['học viên','thực tập'],'thực tập sinh')

In [328]:
data.maCv.unique()

array([nan, 'công nhân', 'cán bộ', 'nhân viên', 'y tá', 'giáo viên',
       'bác sĩ', 'quản lý cấp trung', 'kỹ sư', 'lái xe', 'dược sĩ',
       'khác', 'tksl trong k.trường mỏ', 'hơp đồng thu',
       'uỷ nhiệm thu thuế', 'đầu bếp', 'trung cấp tin', 'gia?m sa?t',
       'qu?n lý xu?ng', 'quan trắc viện', 'kế  toán', 'quân đội',
       'học viên sản xuất vùng 1', 'bảo mẫu', 'thực tập sinh thương mại',
       'kiến trúc sư', 'thu? kho', 'giáo viên', 'biên kịch',
       'hướng dẫn  viên du lịch', 'k? thu?t viờn'], dtype=object)

In [329]:
data.maCv.value_counts()

công nhân                   4135
nhân viên                   1929
giáo viên                    419
quản lý cấp trung            234
kỹ sư                        102
lái xe                        91
y tá                          68
cán bộ                        53
bác sĩ                         9
khác                           9
dược sĩ                        9
đầu bếp                        5
bảo mẫu                        3
quân đội                       2
học viên sản xuất vùng 1       1
thực tập sinh thương mại       1
tksl trong k.trường mỏ         1
hướng dẫn  viên du lịch        1
k? thu?t viờn                  1
quan trắc viện                 1
gia?m sa?t                     1
hơp đồng thu                   1
trung cấp tin                  1
thu? kho                       1
biên kịch                      1
kiến trúc sư                   1
kế  toán                       1
uỷ nhiệm thu thuế              1
giáo viên                     1
qu?n lý xu?ng                  1
Name: maCv, dtype: int64

### 4. Association with Bad Credit

In [345]:
data_groupby_occupation_sum_label = data.groupby(['maCv']).sum()
data_groupby_occupation_sum_label = pd.DataFrame(data_groupby_occupation_sum_label['label'])
data_groupby_occupation_sum_label.columns = ['bad_count']
data_groupby_occupation_sum_label

                          bad_count
maCv
biên kịch                         0
bác sĩ                            0
bảo mẫu                           0
cán bộ                            1
công nhân                        62
dược sĩ                           0
gia?m sa?t                        0
giáo viên                        0
giáo viên                         5
hơp đồng thu                      0
hướng dẫn  viên du lịch           0
học viên sản xuất vùng 1          0
k? thu?t viờn                     0
khác                              0
kiến trúc sư                      0
kế  toán                          0
kỹ sư                             1
lái xe                            1
nhân viên                        24
qu?n lý xu?ng                     0
quan trắc viện                    0
quân đội                          0
quản lý cấp trung                 2
thu? kho                          0
thực tập sinh thương mại          0
tksl trong k.trường mỏ            0
trung cấp tin                     0
uỷ nhiệm thu thuế                 0
y tá                              0
đầu bếp                           0

In [346]:
data_groupby_occupation = data.groupby(['maCv']).count()
data_groupby_occupation = pd.DataFrame(data_groupby_occupation['label'])
data_groupby_occupation

                          label
maCv
biên kịch                     1
bác sĩ                        9
bảo mẫu                       3
cán bộ                       53
công nhân                  4135
dược sĩ                       9
gia?m sa?t                    1
giáo viên                    1
giáo viên                   419
hơp đồng thu                  1
hướng dẫn  viên du lịch       1
học viên sản xuất vùng 1      1
k? thu?t viờn                 1
khác                          9
kiến trúc sư                  1
kế  toán                      1
kỹ sư                       102
lái xe                       91
nhân viên                  1929
qu?n lý xu?ng                 1
quan trắc viện                1
quân đội                      2
quản lý cấp trung           234
thu? kho                      1
thực tập sinh thương mại      1
tksl trong k.trường mỏ        1
trung cấp tin                 1
uỷ nhiệm thu thuế             1
y tá                         68
đầu bếp                       5

In [349]:
data_groupby_occupation = data_groupby_occupation.join(data_groupby_occupation_sum_label)
data_groupby_occupation['bad_ratio'] = data_groupby_occupation.bad_count / data_groupby_occupation.label

ValueError: columns overlap but no suffix specified: Index(['bad_count'], dtype='object')

In [353]:
data_groupby_occupation.sort_values('bad_ratio', ascending=False)

                          label  bad_count  bad_ratio
maCv
cán bộ                       53          1   0.018868
công nhân                  4135         62   0.014994
nhân viên                  1929         24   0.012442
giáo viên                   419          5   0.011933
lái xe                       91          1   0.010989
kỹ sư                       102          1   0.009804
quản lý cấp trung           234          2   0.008547
trung cấp tin                 1          0   0.000000
tksl trong k.trường mỏ        1          0   0.000000
uỷ nhiệm thu thuế             1          0   0.000000
thực tập sinh thương mại      1          0   0.000000
thu? kho                      1          0   0.000000
quân đội                      2          0   0.000000
quan trắc viện                1          0   0.000000
qu?n lý xu?ng                 1          0   0.000000
y tá                         68          0   0.000000
biên kịch                     1          0   0.000000
kế  toán                      1          0   0.000000
bác sĩ                        9          0   0.000000
kiến trúc sư                  1          0   0.000000
khác                          9          0   0.000000
k? thu?t viờn                 1          0   0.000000
học viên sản xuất vùng 1      1          0   0.000000
hướng dẫn  viên du lịch       1          0   0.000000
hơp đồng thu                  1          0   0.000000
giáo viên                    1          0   0.000000
gia?m sa?t                    1          0   0.000000
dược sĩ                       9          0   0.000000
bảo mẫu                       3          0   0.000000
đầu bếp                       5          0   0.000000

In [29]:
data_groupby_district_sum_label

                                      bad_count
province          district
thành phố cần thơ huyện cờ đỏ                 0
                  huyện phong điền            1
                  huyện thới lai              0
                  huyện vĩnh thạnh            0
                  quận bình thuỷ              0
...                                         ...
tỉnh đồng tháp    huyện tháp mười             1
                  huyện tân hồng              1
                  thành phố cao lãnh          0
                  thành phố sa đéc            0
                  thị xã hồng ngự             0

[744 rows x 1 columns]

In [31]:
data_groupby_district = data.groupby(['province','district']).count()
data_groupby_district = pd.DataFrame(data_groupby_district['label'])
data_groupby_district

                                      label
province          district
thành phố cần thơ huyện cờ đỏ            22
                  huyện phong điền       12
                  huyện thới lai         21
                  huyện vĩnh thạnh       19
                  quận bình thuỷ         14
...                                     ...
tỉnh đồng tháp    huyện tháp mười        43
                  huyện tân hồng         22
                  thành phố cao lãnh     42
                  thành phố sa đéc       12
                  thị xã hồng ngự        19

[744 rows x 1 columns]

In [32]:
data_groupby_district_sum_label = data_groupby_district_sum_label.join(data_groupby_district)

In [34]:
data_groupby_district_sum_label['bad_ratio'] = data_groupby_district_sum_label.bad_count / data_groupby_district_sum_label.label

In [36]:
data_groupby_district_sum_label.sort_values('bad_ratio',ascending=False)

                                   bad_count  label  bad_ratio
province        district
tỉnh quảng nam  huyện đông giang           1      2   0.500000
tỉnh hà giang   huyện vị xuyên             1      2   0.500000
tỉnh điện biên  huyện tủa chùa             1      3   0.333333
tỉnh kiên giang huyện giang thành          1      4   0.250000
tỉnh gia lai    huyện đăk đoa              1      4   0.250000
...                                      ...    ...        ...
tỉnh hưng yên   huyện văn giang            0      2   0.000000
                huyện văn lâm              0     10   0.000000
                huyện yên mỹ               0     16   0.000000
                huyện ân thi               0     14   0.000000
tỉnh đồng tháp  thị xã hồng ngự            0     19   0.000000

[744 rows x 3 columns]